#!/bin/bash
# check_running_jobs.sh: if there are no running jobs via slurm, then 
# print and return a 0.  Otherwise, print and return a 1.


result=1 # assume a running job

scontrol listpids
if [ $? == 1 ]; then
    exit 0
fi
exit 1
