#!/bin/bash -x

# use a fixed ROCMPATH 
#
ROCMDIR=/opt/rocm
BINDIR=${ROCMDIR}/bin

# this is where the rvs tests are stored
#CONFDIR=${ROCMDIR}/share/rocm-validation-suite/conf
CONFDIR=rvs/

# this will point to a specific RVS config file.
TEST=${CONFDIR}/mem.conf

# OPTIONS: for the RVS run
OPTIONS=

# now run the test
${BINDIR}/rvs ${OPTIONS} -c ${TEST}
exit $?
